baseurl         =   "https://jre.id.au/"
languageCode    =   "en-us"
title           =   "jre id au"
author          =   "Jamie Reid"
theme           =   "purejam"
Paginate        =   10
#disqusShortname =   "xxxxx"

[params]
  description      = "Maker, coder, writer, musician, 'adult'"
  githubName       = "jamiereid"
  twitterName      = "jambulance"
  email            = "jamie@jre.id.au"
  instagram        = 'jamiereid'
  hideShareOptions = true
